### ISSUE TITLE
Incorrect drawing functions that hasn't max and min value.

### ISSUE THREAD

**Issue by RaEzhov** [nn-students-2021h2/Function_explorer_bot_8#30]
If  max_value = infinity and min_value = -infinity then graph looks like incorrect. Examples in pictures.
![image](https://user-images.githubusercontent.com/79147155/152332520-7c73285d-6f21-4da9-8462-b9a283a96efd.png)
![image](https://user-images.githubusercontent.com/79147155/152332598-de8402bf-2123-4a3a-8cab-e69e2882ad37.png)

**Comment by Korostast** [comment]
It concerns only functions that has huge max or min values on given domain. For example, there is almost no problem with x**2 on domain = [-10; 10], due to 10**2 = 100

Anyway, we cannot predict comfortable y-limit for all the functions. However, there is another solution for this problem. We can allow users to define functions range, so they can config appearance of output picture

I'll try to implement this feature
